name: Pull Request Labels Check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main

jobs:
  label_check:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 2
          labels: "[TR] on develop, [TR] on preprod"
          add_comment: true
          message: "This PR is being prevented from merging because it's missing one of the required labels: {{ provided }}. You'll need to add them before this PR can be merged."
      - name: Prevent merge on failure
        if: failure()
        run: |
          echo "Required labels are missing. Failing the workflow to prevent merge."
          exit 1
